export interface Artwork {
  id: string
  title: string
  year: number
  material: string
  src: string
  width: number
  height: number
  category: "paintings" | "drawings"
}

export const paintings: Artwork[] = [
  {
    id: "p1",
    title: "Ember and Ash",
    year: 2024,
    material: "Oil on canvas, 120 x 150 cm",
    src: "/images/paintings/painting-1.jpg",
    width: 4,
    height: 3,
    category: "paintings",
  },
  {
    id: "p2",
    title: "Morning Veil",
    year: 2024,
    material: "Oil on linen, 90 x 120 cm",
    src: "/images/paintings/painting-2.jpg",
    width: 4,
    height: 3,
    category: "paintings",
  },
  {
    id: "p3",
    title: "Geometry of Silence",
    year: 2023,
    material: "Acrylic on canvas, 100 x 100 cm",
    src: "/images/paintings/painting-3.jpg",
    width: 1,
    height: 1,
    category: "paintings",
  },
  {
    id: "p4",
    title: "The Wanderer",
    year: 2023,
    material: "Oil on canvas, 130 x 90 cm",
    src: "/images/paintings/painting-4.jpg",
    width: 3,
    height: 5,
    category: "paintings",
  },
  {
    id: "p5",
    title: "Wildflowers in October",
    year: 2022,
    material: "Oil on panel, 60 x 50 cm",
    src: "/images/paintings/painting-5.jpg",
    width: 3,
    height: 4,
    category: "paintings",
  },
  {
    id: "p6",
    title: "Tidal Memory",
    year: 2022,
    material: "Mixed media on canvas, 150 x 200 cm",
    src: "/images/paintings/painting-6.jpg",
    width: 4,
    height: 3,
    category: "paintings",
  },
  {
    id: "p7",
    title: "Dusk Over the Atlantic",
    year: 2024,
    material: "Oil on canvas, 60 x 180 cm",
    src: "/images/paintings/painting-7.jpg",
    width: 3,
    height: 1,
    category: "paintings",
  },
  {
    id: "p8",
    title: "Figure in the Mist",
    year: 2023,
    material: "Oil on linen, 160 x 80 cm",
    src: "/images/paintings/painting-8.jpg",
    width: 2,
    height: 3,
    category: "paintings",
  },
  {
    id: "p9",
    title: "Terracotta Fragment",
    year: 2024,
    material: "Acrylic on panel, 50 x 50 cm",
    src: "/images/paintings/painting-9.jpg",
    width: 1,
    height: 1,
    category: "paintings",
  },
  {
    id: "p10",
    title: "Golden Fields, September",
    year: 2023,
    material: "Oil on canvas, 50 x 200 cm",
    src: "/images/paintings/painting-10.jpg",
    width: 5,
    height: 2,
    category: "paintings",
  },
]

export const drawings: Artwork[] = [
  {
    id: "d1",
    title: "Reaching",
    year: 2024,
    material: "Charcoal on paper, 50 x 65 cm",
    src: "/images/drawings/drawing-1.jpg",
    width: 3,
    height: 4,
    category: "drawings",
  },
  {
    id: "d2",
    title: "Rue de la Paix",
    year: 2023,
    material: "Ink on paper, 40 x 30 cm",
    src: "/images/drawings/drawing-2.jpg",
    width: 3,
    height: 4,
    category: "drawings",
  },
  {
    id: "d3",
    title: "Portrait Study IV",
    year: 2023,
    material: "Graphite on paper, 45 x 35 cm",
    src: "/images/drawings/drawing-3.jpg",
    width: 3,
    height: 4,
    category: "drawings",
  },
  {
    id: "d4",
    title: "Autumn Branch",
    year: 2022,
    material: "Pencil and watercolor on paper, 30 x 40 cm",
    src: "/images/drawings/drawing-4.jpg",
    width: 3,
    height: 4,
    category: "drawings",
  },
  {
    id: "d5",
    title: "Sleeping Cat",
    year: 2022,
    material: "Charcoal on paper, 35 x 50 cm",
    src: "/images/drawings/drawing-5.jpg",
    width: 4,
    height: 3,
    category: "drawings",
  },
  {
    id: "d6",
    title: "Reclining Figure II",
    year: 2024,
    material: "Charcoal on paper, 40 x 80 cm",
    src: "/images/drawings/drawing-6.jpg",
    width: 5,
    height: 2,
    category: "drawings",
  },
  {
    id: "d7",
    title: "The Old Oak",
    year: 2023,
    material: "Ink on paper, 30 x 70 cm",
    src: "/images/drawings/drawing-7.jpg",
    width: 2,
    height: 5,
    category: "drawings",
  },
  {
    id: "d8",
    title: "Hands with Cup",
    year: 2024,
    material: "Graphite on toned paper, 25 x 25 cm",
    src: "/images/drawings/drawing-8.jpg",
    width: 1,
    height: 1,
    category: "drawings",
  },
  {
    id: "d9",
    title: "City Horizon",
    year: 2023,
    material: "Pencil on paper, 30 x 90 cm",
    src: "/images/drawings/drawing-9.jpg",
    width: 3,
    height: 1,
    category: "drawings",
  },
]

export const allArtworks: Artwork[] = [...paintings, ...drawings]
